import Image from "next/image";
import Link from "next/link";

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <header className="flex items-center p-2 shadow-md">
          <Link href="/" className="flex items-center space-x-2">
            <Image src="/logo.png" alt="My Tunnel Wait" width={40} height={40} />
            <span className="font-semibold text-lg">My Tunnel Wait</span>
          </Link>
        </header>
        {children}
      </body>
    </html>
  );
}

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
